image: node

stages:
  - setup
  - lint

node-setup:
  stage: setup
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

eslint:
  stage: lint
  script:
    - npm run lint

prettier:
  stage: lint
  script:
    - |
      npm install --global prettier
    - prettier --check "**/*.{js,jsx,ts,tsx,json,md}"
