image: node

stages:
  - setup
  - lint

node-setup:
  stage: setup
  script:
    - npm install
  artifacts:
    paths:
      - node_modules

eslint:
  stage: lint
  script:
    # Install eslint
    - npm install eslint eslint-config-airbnb eslint-config-airbnb/hooks eslint-config-airbnb-typescript eslint-config-prettier
    # Run eslint
    - ./node_modules/.bin/eslint

prettier:
  stage: lint
  script:
    - |
      npm install --global prettier
    - prettier --check "**/*.{js,jsx,ts,tsx,json,md}"